# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- xctool test -workspace Example/SKFormTextField.xcworkspace -scheme SKFormTextField-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- pod lib lint
